import type { ITheme } from 'survey-core'

/** Compact density + brand colors for the side-by-side comparison layout. */
export const compactTheme: ITheme = {
  themeName: 'vike-compact',
  colorPalette: 'light',
  cssVariables: {
    '--sjs2-base-unit-spacing': '4px',
    '--sjs2-base-unit-radius': '4px',

    '--sjs2-layout-component-page-content-area-padding-horizontal': '12px',
    '--sjs2-layout-component-page-content-area-padding-vertical': '8px',
    '--sjs2-layout-component-page-content-area-gap-horizontal': '8px',
    '--sjs2-layout-component-page-content-area-gap-vertical': '8px',
    '--sjs2-layout-component-page-header-padding-horizontal': '12px',
    '--sjs2-layout-component-page-header-padding-vertical': '8px',
    '--sjs2-layout-component-page-header-gap-vertical': '2px',
    '--sjs2-layout-component-page-footer-padding-horizontal': '12px',
    '--sjs2-layout-component-page-footer-padding-vertical': '8px',
    '--sjs2-layout-component-page-footer-action-group-gap': '8px',

    '--sjs2-layout-component-question-box-gap-vertical': '4px',
    '--sjs2-layout-component-question-box-gap-horizontal': '8px',
    '--sjs2-layout-component-question-header-gap-vertical': '2px',
    '--sjs2-layout-component-question-header-gap-horizontal': '4px',
    '--sjs2-layout-component-question-header-side-padding-top': '0',
    '--sjs2-layout-component-question-title-padding-vertical': '0',

    '--sjs2-layout-component-panel-box-padding-horizontal': '0',
    '--sjs2-layout-component-panel-box-padding-top': '4px',
    '--sjs2-layout-component-panel-box-padding-bottom': '4px',
    '--sjs2-layout-component-panel-box-gap-vertical': '8px',
    '--sjs2-layout-component-panel-content-area-padding-horizontal': '0',
    '--sjs2-layout-component-panel-content-area-padding-top': '4px',
    '--sjs2-layout-component-panel-content-area-padding-bottom': '0',
    '--sjs2-layout-component-panel-content-area-gap-horizontal': '8px',
    '--sjs2-layout-component-panel-content-area-gap-vertical': '8px',
    '--sjs2-layout-component-panel-header-padding-top': '0',
    '--sjs2-layout-component-panel-header-padding-bottom': '4px',

    '--sjs2-layout-component-header-box-padding-horizontal': '12px',
    '--sjs2-layout-component-header-box-padding-vertical': '10px',
    '--sjs2-layout-component-header-box-gap-vertical': '2px',

    '--sjs2-layout-component-formbox-medium-padding-vertical': '4px',
    '--sjs2-layout-component-formbox-medium-padding-horizontal': '10px',
    '--sjs2-layout-component-input-medium-content-padding-vertical': '4px',
    '--sjs2-layout-component-input-medium-content-padding-horizontal': '2px',

    '--sjs2-layout-component-labeled-item-box-gap-horizontal': '8px',
    '--sjs2-layout-component-labeled-group-box-gap-vertical': '4px',
    '--sjs2-layout-component-labeled-group-box-padding-vertical': '0',

    '--sjs2-typography-font-size-default': '0.9rem',
    '--sjs2-typography-font-size-component-input-content': '0.9rem',
    '--sjs2-typography-font-size-component-question-description': '0.75rem',
    '--sjs2-typography-font-size-component-page-title': '1.1rem',
    '--sjs2-typography-font-size-component-header-title': '1.25rem',
    '--sjs2-typography-font-size-component-header-description': '0.9rem',
    '--sjs2-typography-font-family-text':
      "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",

    '--sjs2-color-project-brand-600': '#1867c0',
    '--sjs2-color-bg-brand-primary': '#1867c0',
    '--sjs2-color-bg-brand-primary-dim': '#14539a',
    '--sjs2-color-fg-brand-on-primary': '#ffffff',
    '--sjs2-color-fg-brand-primary': '#1867c0',
    '--sjs2-color-component-action-brand-primary-default-bg': '#1867c0',
    '--sjs2-color-component-action-brand-primary-default-label': '#ffffff',
    '--sjs2-color-component-action-brand-primary-default-icon': '#ffffff',
    '--sjs2-color-component-action-brand-primary-hovered-bg': '#14539a',
    '--sjs2-color-component-action-brand-primary-hovered-label': '#ffffff',
    '--sjs2-color-component-action-brand-primary-hovered-icon': '#ffffff',
    '--sjs2-color-component-action-brand-tertiary-surface-default-label': '#1867c0',
    '--sjs2-color-component-action-brand-tertiary-surface-default-icon': '#1867c0',
    '--sjs2-border-effect-component-action-brand-tertiary-surface-default':
      'inset 0 0 0 1px rgba(24, 103, 192, 0.5)',
    '--sjs2-color-component-action-brand-tertiary-surface-hovered-label': '#1867c0',
    '--sjs2-color-component-action-brand-tertiary-surface-hovered-icon': '#1867c0',
    '--sjs2-color-component-action-brand-tertiary-surface-hovered-bg':
      'rgba(24, 103, 192, 0.08)',
    '--sjs2-border-effect-component-action-brand-tertiary-surface-hovered':
      'inset 0 0 0 1px #1867c0',
    '--sjs2-color-component-formbox-focused-border': '#1867c0',
    '--sjs2-border-effect-component-formbox-focused': 'inset 0 0 0 2px #1867c0',
    '--sjs2-color-component-check-true-default-bg': '#1867c0',
    '--sjs2-color-component-check-true-hovered-bg': '#1867c0',
    '--sjs2-color-component-check-true-default-border': '#1867c0',
    '--sjs2-color-component-check-false-focused-border': '#1867c0',
    '--sjs2-border-effect-component-check-true-default': 'inset 0 0 0 2px #1867c0',
    '--sjs2-border-effect-component-check-true-hovered': 'inset 0 0 0 2px #1867c0',
    '--sjs2-border-effect-a11y': '0 0 0 2px #1867c0',
    '--sjs2-color-component-buttongroup-item-true-default-bg': '#1867c0',
    '--sjs2-color-component-buttongroup-item-true-default-border': '#1867c0',
    '--sjs2-color-component-buttongroup-item-true-default-value': '#ffffff',

    '--sjs2-color-utility-surface-survey': 'transparent',
    '--sjs2-color-component-panel-default-bg': 'transparent',
    '--sjs2-color-component-formbox-default-bg': 'transparent',
    '--sjs2-color-component-formbox-focused-bg': 'transparent',
    '--sjs2-color-component-boolean-default-bg': 'transparent',
    '--sjs2-color-component-boolean-item-false-default-bg': 'transparent',
    '--sjs2-color-component-boolean-item-true-default-bg': 'transparent',
  },
}
