export const medicalFormJson = {
  headerView: 'advanced',
  title: 'Patient Intake (SurveyJS)',
  description: 'Tell us about you and your insurance coverage.',
  showProgressBar: true,
  progressBarLocation: 'belowheader',
  progressBarType: 'pages',
  progressBarShowPageTitles: true,
  progressBarShowPageNumbers: true,
  progressBarNavigationTextLocation: 'bottom',
  widthMode: 'responsive',
  questionErrorLocation: 'bottom',
  checkErrorsMode: 'onComplete',
  validationAllowSwitchPages: true,
  pages: [
    {
      name: 'patient',
      title: 'Patient',
      elements: [
        {
          type: 'text',
          name: 'firstName',
          title: 'First name',
          isRequired: true,
          width: '50%',
          minWidth: '100px',
        },
        {
          type: 'text',
          name: 'lastName',
          title: 'Last name',
          isRequired: true,
          startWithNewLine: false,
          width: '50%',
          minWidth: '100px',
        },
        {
          type: 'text',
          name: 'dob',
          title: 'Date of birth',
          inputType: 'date',
          isRequired: true,
          width: '50%',
          minWidth: '100px',
        },
        {
          type: 'radiogroup',
          name: 'sex',
          title: 'Sex assigned at birth',
          startWithNewLine: false,
          width: '50%',
          minWidth: '100px',
          colCount: 0,
          choices: [
            { value: 'f', text: 'Female' },
            { value: 'm', text: 'Male' },
          ],
        },
        {
          type: 'text',
          name: 'phone',
          title: 'Mobile phone',
          inputType: 'tel',
          maskType: 'pattern',
          maskSettings: { pattern: '+1 (999) 999-9999' },
        },
        {
          type: 'dropdown',
          name: 'preferredContact',
          title: 'Preferred contact method',
          startWithNewLine: false,
          choices: ['Phone', 'Email', 'Text message'],
        },
      ],
    },
    {
      name: 'insurance',
      title: 'Insurance',
      elements: [
        {
          type: 'panel',
          name: 'primaryInsurance',
          title: 'Primary insurance',
          elements: [
            {
              type: 'text',
              name: 'carrier',
              title: 'Insurance carrier',
              isRequired: true,
              width: '50%',
              minWidth: '100px',
            },
            {
              type: 'text',
              name: 'memberId',
              title: 'Member ID',
              isRequired: true,
              startWithNewLine: false,
              width: '50%',
              minWidth: '100px',
            },
            {
              type: 'text',
              name: 'groupNumber',
              title: 'Group number',
              width: '50%',
            },
            {
              type: 'radiogroup',
              name: 'relationshipToInsured',
              title: 'Patient is the…',
              colCount: 0,
              defaultValue: 'self',
              choices: [
                { value: 'self', text: 'Policyholder' },
                { value: 'spouse', text: 'Spouse' },
                { value: 'dependent', text: 'Dependent' },
              ],
            },
          ],
        },
        {
          type: 'boolean',
          name: 'hasSecondary',
          title: 'Do you have secondary insurance?',
          defaultValue: false,
          renderAs: 'checkbox',
          titleLocation: 'hidden'
        },
        {
          type: 'panel',
          name: 'secondaryInsurance',
          title: 'Secondary insurance',
          visibleIf: '{hasSecondary} = true',
          elements: [
            {
              type: 'text',
              name: 'carrier2',
              title: 'Insurance carrier',
              isRequired: true,
              width: '50%',
              minWidth: '100px',
            },
            {
              type: 'text',
              name: 'memberId2',
              title: 'Member ID',
              isRequired: true,
              startWithNewLine: false,
              width: '50%',
              minWidth: '100px',
            },
          ],
        },
      ],
    },
    {
      name: 'history',
      title: 'History',
      elements: [
        {
          type: 'matrix',
          name: 'medicalHistory',
          title: 'Have you ever been diagnosed with any of the following?',
          displayMode: 'table',
          columns: [
            { value: 'yes', text: 'Yes' },
            { value: 'no', text: 'No' },
            { value: 'unsure', text: 'Unsure' },
          ],
          rows: [
            { value: 'diabetes', text: 'Diabetes' },
            { value: 'hypertension', text: 'High blood pressure' },
            { value: 'asthma', text: 'Asthma' },
            { value: 'heart', text: 'Heart disease' },
          ],
        },
        {
          type: 'matrixdynamic',
          name: 'allergies',
          title: 'Allergies',
          addRowText: 'Add allergy',
          rowCount: 0,
          showHeader: false,
          noRowsText: 'No allergies added.',
          columns: [
            {
              name: 'allergen',
              title: 'Allergen',
              cellType: 'text',
              isRequired: true,
              placeholder: 'Allergen *',
            },
            {
              name: 'severity',
              title: 'Severity',
              cellType: 'dropdown',
              choices: ['Mild', 'Moderate', 'Severe'],
              placeholder: 'Severity...',
            },
            { name: 'reaction', title: 'Reaction', cellType: 'text', placeholder: 'Reaction' },
          ],
        },
        {
          type: 'comment',
          name: 'currentMedications',
          title: 'Current medications',
          rows: 3,
        },
      ],
    },
    {
      name: 'consent',
      title: 'Consent',
      elements: [
        {
          type: 'boolean',
          name: 'consentTreatment',
          title: 'I consent to treatment',
          renderAs: 'checkbox',
          titleLocation: 'hidden',
          isRequired: true,
        },
        {
          type: 'boolean',
          name: 'consentPrivacy',
          title: 'I acknowledge the privacy practices (HIPAA)',
          renderAs: 'checkbox',
          titleLocation: 'hidden',
          isRequired: true,
        },
        {
          type: 'signaturepad',
          name: 'signature',
          title: 'Signature',
        },
        {
          type: 'text',
          name: 'signedDate',
          title: 'Date',
          inputType: 'date',
          startWithNewLine: false,
        },
      ],
    },
  ],
  completedHtml: '<h4>Thank you. Your intake form has been submitted.</h4>',
} as const

export const medicalFormSample = {
  firstName: 'Jordan',
  lastName: 'Avery',
  dob: '1990-06-15',
  sex: 'f',
  phone: '+1 (415) 555-0142',
  preferredContact: 'Email',
  carrier: 'BlueCross BlueShield',
  memberId: 'BCBS-884512200',
  groupNumber: 'GRP-55821',
  relationshipToInsured: 'self',
  hasSecondary: true,
  carrier2: 'Aetna',
  memberId2: 'AET-220148',
  medicalHistory: {
    diabetes: 'no',
    hypertension: 'yes',
    asthma: 'no',
    heart: 'unsure',
  },
  allergies: [{ allergen: 'Penicillin', severity: 'Severe', reaction: 'Anaphylaxis' }],
  currentMedications: 'Lisinopril 10mg daily',
  consentTreatment: true,
  consentPrivacy: true,
  signedDate: '2026-07-24',
}
